"""Auto-populate related: fields and generate _GRAPH.md.

Finds related entries by shared domains and tags.
Optionally uses semantic similarity via engine.embed() for deeper matching.
"""

import re
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Optional

import yaml

from dream_cycle.config import load_config, Config
from dream_cycle.index import collect_entries, _first_sentence


def _normalize_tags(tags) -> set:
    """Normalize a list of tags to lowercase set."""
    if not tags:
        return set()
    if isinstance(tags, str):
        tags = [tags]
    return {t.strip().lower() for t in tags if isinstance(t, str)}


def find_related(entry: dict, all_entries: list[dict], max_related: int = 5) -> list[str]:
    """Find related entries by shared domains and tags."""
    my_domains = _normalize_tags(entry.get('domain', []))
    my_tags = _normalize_tags(entry.get('tags', []))
    my_path = str(entry['_rel_path'])

    scored = []
    for other in all_entries:
        other_path = str(other['_rel_path'])
        if other_path == my_path:
            continue

        other_domains = _normalize_tags(other.get('domain', []))
        other_tags = _normalize_tags(other.get('tags', []))

        # Score by overlap
        domain_overlap = len(my_domains & other_domains)
        tag_overlap = len(my_tags & other_tags)
        score = domain_overlap * 3 + tag_overlap  # domains weighted higher

        if score > 0:
            scored.append((score, other_path))

    scored.sort(key=lambda x: -x[0])
    return [path for _, path in scored[:max_related]]


def update_frontmatter_related(path: Path, related: list[str]) -> None:
    """Update the related: field in a wiki entry's frontmatter.

    Bumps `updated:` to today when the file is actually rewritten. The
    caller (run_crosslink) already filters by "did the related list
    change", so reaching this function means the rewrite is real — a
    new connection has been discovered or a stale link removed. That
    constitutes a semantic change to the entry's discoverability
    surface and downstream metrics (the dashboard's per-day knowledge
    & taste flow chart) should reflect it.

    Before this fix, crosslink rewrote files but left `updated:` stuck
    at the original distillation date, so the dashboard read mtime ≠
    `updated:` and either over-counted via mtime or, after the
    intake-side fix that trusts frontmatter, dropped the activity
    silently. Bumping `updated:` here lets the producer be the source
    of truth and the consumer trust it.
    """
    content = path.read_text()
    if not content.startswith('---'):
        return

    parts = content.split('---', 2)
    if len(parts) < 3:
        return

    try:
        fm = yaml.safe_load(parts[1])
        if not isinstance(fm, dict):
            return
    except Exception:
        return

    fm['related'] = related
    fm['updated'] = date.today().isoformat()

    # Rebuild file
    new_fm = yaml.dump(fm, default_flow_style=False, allow_unicode=True, sort_keys=False)
    new_content = f"---\n{new_fm}---\n{parts[2]}"
    path.write_text(new_content)


def generate_graph(entries: list[dict]) -> str:
    """Generate _GRAPH.md — adjacency list of the knowledge graph."""
    lines = [
        "# Digital Me — Knowledge Graph",
        "> Auto-generated by dream_cycle/crosslink.py",
        "",
    ]

    # Group by domain for visual clarity
    by_domain = defaultdict(list)
    for e in entries:
        by_domain[e['_domain']].append(e)

    for domain in sorted(by_domain.keys()):
        lines.append(f"## {domain}/")
        for e in by_domain[domain]:
            title = e.get('title', 'Untitled')
            related = e.get('related', [])
            if related:
                rel_str = ", ".join(f"[{r}]({r})" for r in related)
                lines.append(f"- **{title}** -> {rel_str}")
            else:
                lines.append(f"- **{title}** (orphan)")
        lines.append("")

    # Orphan summary
    orphans = [e for e in entries if not e.get('related')]
    if orphans:
        lines.append(f"## Orphans ({len(orphans)} entries with no links)")
        for e in orphans:
            lines.append(f"- {e.get('title', 'Untitled')} ({e['_rel_path']})")

    return "\n".join(lines)


def generate_overviews(config: Config, entries: list[dict]) -> int:
    """Generate _OVERVIEW.md for each wiki domain directory.

    Wiki-only surface: the tastes tree stays flat (leaves + status flips,
    no machine files), and a taste-only domain (e.g. tastes/storytelling/)
    has no wiki/<domain>/ directory — writing there raised ENOENT and
    killed the whole crosslink step from 2026-07-09 on. Splitting on the
    `_tree` tag also keeps taste leaves out of wiki overviews, where their
    `path.name` relative links would dangle.
    """
    by_domain = defaultdict(list)
    for e in entries:
        if e.get('_tree') != 'wiki':
            continue
        by_domain[e['_domain']].append(e)

    count = 0
    for domain, domain_entries in by_domain.items():
        if domain == "root":
            continue

        domain_dir = config.wiki_dir / domain
        if not domain_dir.is_dir():
            continue
        overview_path = domain_dir / "_OVERVIEW.md"

        lines = [
            f"# {domain.replace('-', ' ').title()}",
            f"> {len(domain_entries)} entries in this domain",
            "",
            "## Entries",
        ]

        for e in domain_entries:
            title = e.get('title', 'Untitled')
            path = e['_path'].name
            summary = _first_sentence(e.get('_body', ''))
            lines.append(f"- [{title}]({path}) — {summary}")

        lines.append("")
        overview_path.write_text("\n".join(lines))
        count += 1

    return count


def run_crosslink(config: Optional[Config] = None) -> dict:
    """Run cross-linking: find related, update frontmatter, generate graph."""
    config = config or load_config()
    entries = collect_entries(config)

    print(f"Cross-linking {len(entries)} entries...")

    # Find related for each entry
    updated = 0
    for e in entries:
        related = find_related(e, entries)
        if related != (e.get('related') or []):
            update_frontmatter_related(e['_path'], related)
            e['related'] = related
            updated += 1

    # Generate graph
    graph_content = generate_graph(entries)
    graph_path = config.wiki_root / "_GRAPH.md"
    graph_path.write_text(graph_content)

    # Generate domain overviews
    overview_count = generate_overviews(config, entries)

    print(f"  Updated {updated} entries with related links")
    print(f"  Generated _GRAPH.md")
    print(f"  Generated {overview_count} domain _OVERVIEW.md files")

    orphans = sum(1 for e in entries if not e.get('related'))
    return {
        "entries": len(entries),
        "updated": updated,
        "orphans": orphans,
        "overviews": overview_count,
    }


if __name__ == "__main__":
    run_crosslink()
