"""Generate _INDEX.md and _STATS.md from wiki/ entries.

Scans all wiki domain directories, reads frontmatter from each entry,
generates a master index grouped by domain with Active Policies at top.
"""

import re
from collections import defaultdict
from datetime import date, datetime
from pathlib import Path
from typing import Optional

import yaml

from dream_cycle.config import load_config, Config


# Hard caps to prevent _INDEX.md from crowding agent context. Mirrors the
# discipline Claude Code applies to MEMORY.md (200 lines / 25KB) but at 2x
# since this index serves cross-agent retrieval, not single-project memory.
# When over, generate_index demotes content in this order:
#   1. Drop Stale section (it duplicates _STATS.md anyway).
#   2. Drop per-entry summaries — leave just `- [Title](path)`.
#   3. Cap per-domain to PER_DOMAIN_CAP entries with `+N more` pointer.
# Active Policies are never demoted — that is the whole point of the section.
MAX_INDEX_LINES = 400
MAX_INDEX_BYTES = 50_000
PER_DOMAIN_CAP = 8


def _parse_frontmatter(path: Path) -> Optional[dict]:
    """Read YAML frontmatter from a wiki entry file."""
    try:
        content = path.read_text()
    except Exception:
        return None
    if not content.startswith('---'):
        return None
    parts = content.split('---', 2)
    if len(parts) < 3:
        return None
    try:
        fm = yaml.safe_load(parts[1])
        if not isinstance(fm, dict):
            return None
        fm['_path'] = path
        fm['_body'] = parts[2].strip()
        return fm
    except Exception:
        return None


def _first_sentence(body: str) -> str:
    """Extract first meaningful sentence from body for summary."""
    # Skip ## headers, get first real content line
    for line in body.split('\n'):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        # Truncate to first sentence
        sentence = re.split(r'[.!?\n]', line)[0].strip()
        if len(sentence) > 100:
            sentence = sentence[:97] + "..."
        return sentence
    return ""


def _days_ago(date_str) -> Optional[int]:
    """Calculate days since a date string."""
    if not date_str:
        return None
    try:
        if isinstance(date_str, date):
            d = date_str
        else:
            d = datetime.strptime(str(date_str), "%Y-%m-%d").date()
        return (date.today() - d).days
    except Exception:
        return None


def collect_entries(config: Config) -> list[dict]:
    """Scan wiki/ and tastes/ for all entries with frontmatter.

    Per NUX scope-down §A: tastes were unified with the wiki under
    ~/digital-me/tastes/<domain>/<slug>.md and share the wiki frontmatter
    schema. _INDEX.md / _STATS.md aggregate both trees so the dashboard's
    distribution and counts metrics see one corpus. Each entry's `_tree`
    field tags 'wiki' or 'tastes' so consumers can split when needed.
    """
    entries = []
    wiki = config.wiki_dir
    if wiki.exists():
        for md_file in sorted(wiki.rglob("*.md")):
            if md_file.name.startswith('_'):
                continue
            fm = _parse_frontmatter(md_file)
            if fm:
                fm['_rel_path'] = md_file.relative_to(wiki)
                fm['_domain'] = md_file.parent.name if md_file.parent != wiki else "root"
                fm['_tree'] = 'wiki'
                entries.append(fm)

    # Tastes tree lives next to the wiki under the same parent (~/digital-me/).
    tastes = wiki.parent / "tastes" if wiki.name == "wiki" else wiki.parent / "tastes"
    if tastes.exists():
        for md_file in sorted(tastes.rglob("*.md")):
            if md_file.name.startswith('_'):
                continue
            fm = _parse_frontmatter(md_file)
            if fm:
                fm['_rel_path'] = md_file.relative_to(tastes)
                fm['_domain'] = md_file.parent.name if md_file.parent != tastes else "root"
                fm['_tree'] = 'tastes'
                entries.append(fm)

    return entries


def _build_header(today: str, total: int, n_domains: int, n_stale: int) -> list[str]:
    return [
        f"# Digital Me — Knowledge Index",
        f"> Auto-generated by dream_cycle/index.py | Last updated: {today}",
        f"> {total} entries | {n_domains} domains | {n_stale} stale",
        "",
    ]


def _build_policies(policies: list[dict]) -> list[str]:
    """Active Policies section. NEVER demoted — these are mandatory rules."""
    if not policies:
        return []
    lines = [
        "=" * 60,
        "## ACTIVE POLICIES (MANDATORY)",
        "=" * 60,
        "",
        "> These rules apply to all agents. Read them before any task.",
        "> Source: entries marked `priority: always` in the wiki.",
        "",
    ]
    for e in policies:
        title = e.get('title', 'Untitled')
        path = e['_rel_path']
        body = e.get('_body', '')
        rule_match = re.search(
            r'^## Rule\s*\n(.+?)(?=\n## [A-Z]|\Z)',
            body, re.DOTALL | re.MULTILINE,
        )
        rule_text = rule_match.group(1).strip() if rule_match else _first_sentence(body)
        lines.append(f"### {title}")
        lines.append(f"*[Full entry: {path}]*")
        lines.append("")
        lines.append(rule_text)
        lines.append("")
    lines.append("=" * 60)
    lines.append("")
    return lines


def _build_per_domain(
    by_domain: dict[str, list[dict]],
    *,
    include_summary: bool,
    cap_per_domain: Optional[int],
) -> list[str]:
    """Domain sections. Demotion knobs: drop per-entry summary, cap entries per domain."""
    lines: list[str] = []
    for domain in sorted(by_domain.keys()):
        domain_entries = sorted(
            by_domain[domain],
            key=lambda e: str(e.get('updated', e.get('created', '0'))),
            reverse=True,
        )
        total_in_domain = len(domain_entries)
        if cap_per_domain is not None and total_in_domain > cap_per_domain:
            shown = domain_entries[:cap_per_domain]
            elided = total_in_domain - cap_per_domain
        else:
            shown = domain_entries
            elided = 0

        lines.append(f"## {domain}/ ({total_in_domain} entries)")
        for e in shown:
            title = e.get('title', 'Untitled')
            path = e['_rel_path']
            # Type-tag prefix mirrors Claude Code's memoryScan manifest format
            # ([${m.type}] filename: description) — gives a glance-level signal
            # of WHAT KIND of knowledge an entry is without reading the body.
            t = e.get('type')
            type_tag = f"[{t}] " if t else ""
            if include_summary:
                summary = _first_sentence(e.get('_body', ''))
                lines.append(f"- {type_tag}[{title}]({path}) — {summary}")
            else:
                lines.append(f"- {type_tag}[{title}]({path})")
        if elided > 0:
            lines.append(f"- _+{elided} more — see {domain}/ directory_")
        lines.append("")
    return lines


def _build_stale(stale: list[dict], threshold: int) -> list[str]:
    """Stale section. Demotion target: dropped first since _STATS.md has same info."""
    if not stale:
        return []
    lines = [f"## Stale (not updated in {threshold}+ days)"]
    for e in stale:
        title = e.get('title', 'Untitled')
        path = e['_rel_path']
        updated = e.get('updated') or e.get('created')
        days = _days_ago(updated)
        lines.append(f"- [{title}]({path}) — last updated: {updated} ({days}d ago)")
    lines.append("")
    return lines


def _within_caps(lines: list[str]) -> tuple[bool, int, int]:
    """Return (fits, rendered_line_count, byte_count).

    `lines` is the builder's list-of-strings, but elements can themselves
    contain newlines (Active Policy rule bodies are multi-line). Count the
    rendered text's newlines, not list length — that's what readers see.
    """
    text = "\n".join(lines)
    rendered_lines = text.count("\n") + 1
    # Cap on UTF-8 byte length, not code-point length — em-dashes and other
    # non-ASCII run 3 bytes apiece and meaningfully widen titles.
    byte_count = len(text.encode("utf-8"))
    return (
        rendered_lines <= MAX_INDEX_LINES and byte_count <= MAX_INDEX_BYTES,
        rendered_lines,
        byte_count,
    )


# Demotion strategies tried in order. Each tuple is (label, include_stale,
# include_summary, cap_per_domain). The first one that fits both caps wins;
# if none fit, the last (most aggressive) is used and a WARNING banner is
# appended so the truncation is visible to readers.
_DEMOTION_STAGES: list[tuple[str, bool, bool, Optional[int]]] = [
    ("full",        True,  True,  None),
    ("no_stale",    False, True,  None),
    ("no_summary",  False, False, None),
    ("capped",      False, False, PER_DOMAIN_CAP),
]


def generate_index(config: Config, entries: list[dict]) -> tuple[str, dict]:
    """Generate _INDEX.md content with progressive demotion under size caps.

    Returns (content, demotion_info) so generate_stats can surface which stage
    fired. demotion_info: {stage, line_count, byte_count, was_truncated}.
    """
    today = date.today().isoformat()
    total = len(entries)

    threshold = config.dream_cycle.staleness_threshold_days
    stale = []
    for e in entries:
        updated = e.get('updated') or e.get('created')
        days = _days_ago(updated)
        if days is not None and days > threshold:
            stale.append(e)

    by_domain: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_domain[e['_domain']].append(e)

    policies = [e for e in entries if e.get('priority') == 'always']

    header = _build_header(today, total, len(by_domain), len(stale))
    policies_lines = _build_policies(policies)  # never demoted

    chosen_stage = _DEMOTION_STAGES[-1]
    chosen_lines: list[str] = []
    for stage in _DEMOTION_STAGES:
        _, include_stale, include_summary, cap = stage
        body = _build_per_domain(
            by_domain,
            include_summary=include_summary,
            cap_per_domain=cap,
        )
        if include_stale:
            body.extend(_build_stale(stale, threshold))
        candidate = header + policies_lines + body
        fits, line_count, byte_count = _within_caps(candidate)
        chosen_lines = candidate
        chosen_stage = stage
        if fits:
            break

    fits, line_count, byte_count = _within_caps(chosen_lines)
    if not fits:
        # Most-aggressive stage still exceeds caps (Active Policies + many
        # domains). Append banner so readers see the truncation explicitly.
        chosen_lines.append(
            f"> WARNING: _INDEX.md exceeds caps even after maximum demotion "
            f"({line_count} lines, {byte_count} bytes; caps: {MAX_INDEX_LINES} lines, "
            f"{MAX_INDEX_BYTES} bytes). Active Policies + domain count is the load — "
            f"either reduce Active Policies or split domains."
        )

    info = {
        "stage": chosen_stage[0],
        "line_count": line_count,
        "byte_count": byte_count,
        "was_truncated": chosen_stage[0] != "full",
    }
    return "\n".join(chosen_lines), info


def generate_stats(config: Config, entries: list[dict], index_info: Optional[dict] = None) -> str:
    """Generate _STATS.md content."""
    today = date.today().isoformat()
    total = len(entries)

    # Domain counts
    by_domain = defaultdict(int)
    for e in entries:
        by_domain[e['_domain']] += 1

    # Priority counts
    policies = sum(1 for e in entries if e.get('priority') == 'always')

    # Citation distribution
    citations = [e.get('citations', 0) or 0 for e in entries]
    total_citations = sum(citations)
    zero_citation = sum(1 for c in citations if c == 0)

    # Source distribution
    by_source = defaultdict(int)
    for e in entries:
        by_source[e.get('source', 'unknown')] += 1

    # Freshness
    threshold = config.dream_cycle.staleness_threshold_days
    stale = 0
    fresh = 0
    for e in entries:
        updated = e.get('updated') or e.get('created')
        days = _days_ago(updated)
        if days is not None and days > threshold:
            stale += 1
        else:
            fresh += 1

    lines = [
        f"# Digital Me — Stats",
        f"> Auto-generated | {today}",
        "",
        f"## Overview",
        f"- **Total entries:** {total}",
        f"- **Active policies:** {policies}",
        f"- **Domains:** {len(by_domain)}",
        f"- **Fresh:** {fresh} | **Stale:** {stale}",
        "",
    ]

    if index_info:
        stage = index_info.get("stage", "full")
        lc = index_info.get("line_count", 0)
        bc = index_info.get("byte_count", 0)
        truncated = index_info.get("was_truncated", False)
        marker = "⚠ TRUNCATED" if truncated else "ok"
        lines.extend([
            f"## Index Health",
            f"- **Stage:** {stage} ({marker})",
            f"- **Size:** {lc} lines / {bc} bytes (caps: {MAX_INDEX_LINES} lines, {MAX_INDEX_BYTES} bytes)",
            "",
        ])

    lines.append(f"## Domains")
    for domain, count in sorted(by_domain.items(), key=lambda x: -x[1]):
        lines.append(f"- {domain}: {count}")

    lines.extend([
        "",
        f"## Citations",
        f"- Total citations: {total_citations}",
        f"- Zero-citation entries: {zero_citation}",
        f"- Average: {total_citations/max(total,1):.1f}",
        "",
        f"## Sources",
    ])
    for source, count in sorted(by_source.items(), key=lambda x: -x[1]):
        lines.append(f"- {source}: {count}")

    return "\n".join(lines)


def run_index(config: Optional[Config] = None) -> dict:
    """Generate _INDEX.md and _STATS.md."""
    config = config or load_config()
    entries = collect_entries(config)

    index_content, index_info = generate_index(config, entries)
    stats_content = generate_stats(config, entries, index_info=index_info)

    index_path = config.wiki_root / "_INDEX.md"
    stats_path = config.wiki_root / "_STATS.md"

    index_path.write_text(index_content)
    stats_path.write_text(stats_content)

    stage = index_info.get("stage", "full")
    lc = index_info.get("line_count", 0)
    bc = index_info.get("byte_count", 0)
    print(f"Generated _INDEX.md ({len(entries)} entries, stage={stage}, {lc} lines / {bc} bytes)")
    print(f"Generated _STATS.md")

    return {
        "entries": len(entries),
        "index": str(index_path),
        "stats": str(stats_path),
        "index_stage": stage,
        "index_line_count": lc,
        "index_byte_count": bc,
    }


if __name__ == "__main__":
    run_index()
