/**
 * runtime-openclaw installer paths + plugin manifest constants.
 *
 * Emits TWO openclaw plugins:
 *   - digital-me-brain   (operations: tasks, traces, learnings_capture)
 *   - digital-me-recall  (knowledge auto-application: 4 hooks)
 *
 * The actual filesystem install (copy templates into the user's
 * openclaw extensions dir) lives in the digital-me CLI; this module
 * exposes the source paths + the well-known target dirnames so the CLI
 * can stay pure-data.
 */

import { fileURLToPath } from "node:url";
import path from "node:path";

export const PACKAGE_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

export const TEMPLATES_DIR = path.join(PACKAGE_ROOT, "templates");

// ─── digital-me-brain ────────────────────────────────────────────────────

export const BRAIN_TEMPLATES_DIR = path.join(TEMPLATES_DIR, "brain");

export const BRAIN_MANIFEST_TEMPLATE = path.join(
  BRAIN_TEMPLATES_DIR,
  "openclaw.plugin.json",
);

export const BRAIN_ENTRY_TEMPLATE = path.join(BRAIN_TEMPLATES_DIR, "index.mjs");

export const BRAIN_PLUGIN_DIRNAME = "digital-me-brain";

export const BRAIN_INSTALL_FILES = [
  { src: BRAIN_MANIFEST_TEMPLATE, target: "openclaw.plugin.json" },
  { src: BRAIN_ENTRY_TEMPLATE, target: "index.mjs" },
] as const;

// ─── digital-me-recall ───────────────────────────────────────────────────

export const RECALL_TEMPLATES_DIR = path.join(TEMPLATES_DIR, "recall");

export const RECALL_MANIFEST_TEMPLATE = path.join(
  RECALL_TEMPLATES_DIR,
  "openclaw.plugin.json",
);

export const RECALL_ENTRY_TEMPLATE = path.join(
  RECALL_TEMPLATES_DIR,
  "index.mjs",
);

export const RECALL_PLUGIN_DIRNAME = "digital-me-recall";

export const RECALL_INSTALL_FILES = [
  { src: RECALL_MANIFEST_TEMPLATE, target: "openclaw.plugin.json" },
  { src: RECALL_ENTRY_TEMPLATE, target: "index.mjs" },
] as const;

// ─── Per-plugin descriptors ──────────────────────────────────────────────

export interface PluginInstallDescriptor {
  /** Plugin id (matches the manifest's id field, used as install dirname). */
  pluginDirname: string;
  /** Files copied verbatim into <extensionsDir>/<pluginDirname>/. */
  installFiles: ReadonlyArray<{ src: string; target: string }>;
  /** Human-readable name used in installer logs. */
  displayName: string;
}

/**
 * All plugins this runtime-openclaw package emits. The CLI iterates over
 * this when running `digital-me install --runtime openclaw`.
 */
export const PLUGINS: readonly PluginInstallDescriptor[] = [
  {
    pluginDirname: BRAIN_PLUGIN_DIRNAME,
    installFiles: BRAIN_INSTALL_FILES,
    displayName: "digital-me-brain",
  },
  {
    pluginDirname: RECALL_PLUGIN_DIRNAME,
    installFiles: RECALL_INSTALL_FILES,
    displayName: "digital-me-recall",
  },
];

// ─── Generated package.json for the install target ───────────────────────

/**
 * Absolute on-disk roots of the workspace packages the plugin entries
 * import. Used to build the extension's package.json with `file:` deps
 * so Node's ESM loader can resolve `@digital-me/*` bare specifiers from
 * inside the openclaw extensions dir. openclaw's plugin loader does not
 * bundle deps, so a `node_modules` tree must sit alongside `index.mjs`.
 */
export interface ResolvedPackagePaths {
  brainOrchestrator: string;
  runtimeOpenclaw: string;
  contracts: string;
}

/**
 * Generate the package.json that goes into a plugin's install dir. Both
 * digital-me-brain and digital-me-recall depend on the same three
 * @digital-me/* packages, so we share the descriptor (different `name`
 * field per plugin keeps `npm install` outputs distinct).
 */
export function buildExtensionPackageJson(
  paths: ResolvedPackagePaths,
  pluginDirname: string = BRAIN_PLUGIN_DIRNAME,
): Record<string, unknown> {
  return {
    name: `${pluginDirname}-extension`,
    version: "0.0.0-local",
    private: true,
    type: "module",
    description: `Local install of ${pluginDirname} into openclaw's extensions directory. Auto-generated by \`digital-me install --runtime openclaw\`.`,
    // openclaw 2026.5+ requires this field on plugins under
    // `<extensionsDir>/`; without it the gateway's discovery skips
    // hooks-only plugins (tool-contract plugins like the brain happen
    // to be discovered via the manifest's contracts.tools field, which
    // hides the bug for tool-providing plugins).
    openclaw: { extensions: ["./index.mjs"] },
    dependencies: {
      "@digital-me/brain-orchestrator": `file:${paths.brainOrchestrator}`,
      "@digital-me/runtime-openclaw": `file:${paths.runtimeOpenclaw}`,
      "@digital-me/contracts": `file:${paths.contracts}`,
      yaml: "^2.6.0",
    },
  };
}

/** Filename for the generated package.json. */
export const EXTENSION_PACKAGE_JSON = "package.json";

// ─── Back-compat aliases ─────────────────────────────────────────────────
// Pre-recall code paths referred to a single brain plugin via these names.
// Keep them as aliases pointing at the brain plugin so callers that
// haven't switched to the new PLUGINS[] iteration still work.

/** @deprecated use BRAIN_MANIFEST_TEMPLATE */
export const MANIFEST_TEMPLATE = BRAIN_MANIFEST_TEMPLATE;
/** @deprecated use BRAIN_ENTRY_TEMPLATE */
export const ENTRY_TEMPLATE = BRAIN_ENTRY_TEMPLATE;
/** @deprecated use BRAIN_PLUGIN_DIRNAME */
export const PLUGIN_DIRNAME = BRAIN_PLUGIN_DIRNAME;
/** @deprecated use BRAIN_INSTALL_FILES */
export const INSTALL_FILES = BRAIN_INSTALL_FILES;
