/**
 * Materialize the digital-me openclaw plugin overlay into an extensions dir.
 *
 * Extracted from the CLI bin so it can be unit/e2e-tested directly (the bin
 * runs `main()` on import). Shared by the `install` and `update` commands.
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

import { build as esbuildBuild } from "esbuild";
import {
  DEFAULT_WORKER_SCRIPT as OPENCLAW_CLI_EXEC_WORKER_SCRIPT,
  EXTENSION_PACKAGE_JSON as OPENCLAW_EXTENSION_PACKAGE_JSON,
  OPENCLAW_MIN_HOST_VERSION,
  PLUGINS as OPENCLAW_PLUGINS,
  PREBUILT_DIR as OPENCLAW_PREBUILT_DIR,
} from "@digital-me/runtime-openclaw";

/**
 * Bundle + write every PLUGINS entry into `extensionsDir`. Shared by the
 * `install` and `update` commands.
 *
 * We esbuild-bundle the plugin entry into a single self-contained file
 * alongside a minimal package.json. This matches openclaw's own
 * dist/extensions/*\/index.js pattern: no node_modules in the install
 * dir, no symlinks, no dependency resolution at gateway startup, no
 * plugin-safety-scan rejection. Works identically whether the
 * @digital-me/* packages live in a workspace or are installed from
 * npm — bundling resolves all of that at install time.
 *
 * Externals: openclaw/* (provided by the gateway runtime) and node:*
 * built-ins. Everything else (yaml, typebox, @digital-me/*) gets
 * inlined into the bundled output.
 */
export async function materializeOpenclawOverlay(
  target: string,
): Promise<number> {
  for (const plugin of OPENCLAW_PLUGINS) {
    const pluginDir = path.join(target, plugin.pluginDirname);
    mkdirSync(pluginDir, { recursive: true });

    // Copy the manifest verbatim (not bundled — openclaw reads it as JSON)
    const manifestFile = plugin.installFiles.find(
      (f) => f.target === "openclaw.plugin.json",
    );
    if (!manifestFile) {
      console.error(
        `install openclaw: ${plugin.displayName} has no manifest in INSTALL_FILES`,
      );
      return 2;
    }
    writeFileSync(
      path.join(pluginDir, "openclaw.plugin.json"),
      readFileSync(manifestFile.src, "utf-8"),
      "utf-8",
    );

    // Bundle index.mjs
    const entryFile = plugin.installFiles.find(
      (f) => f.target === "index.mjs",
    );
    if (!entryFile) {
      console.error(
        `install openclaw: ${plugin.displayName} has no entry in INSTALL_FILES`,
      );
      return 2;
    }
    // Published-CLI layout ships publish-time pre-bundled entries (no
    // workspace to resolve imports against) — copy those when present.
    const prebuiltEntry = path.join(
      OPENCLAW_PREBUILT_DIR,
      plugin.pluginDirname,
      "index.mjs",
    );
    if (existsSync(prebuiltEntry)) {
      copyFileSync(prebuiltEntry, path.join(pluginDir, "index.mjs"));
      const pkgJsonPrebuilt = {
        name: `${plugin.pluginDirname}-extension`,
        version: "0.0.0-local",
        private: true,
        type: "module",
        description: `Bundled install of ${plugin.pluginDirname} (publish-time esbuild bundle). Auto-generated by \`digital-me install --runtime openclaw\`.`,
        openclaw: { extensions: ["./index.mjs"] },
        // Enforced compatibility floor — openclaw refuses to load on an older
        // host. Source of truth: @digital-me/runtime-openclaw compat.ts.
        install: { minHostVersion: OPENCLAW_MIN_HOST_VERSION },
      };
      writeFileSync(
        path.join(pluginDir, OPENCLAW_EXTENSION_PACKAGE_JSON),
        JSON.stringify(pkgJsonPrebuilt, null, 2) + "\n",
        "utf-8",
      );
      console.log(`[OK] installed ${plugin.displayName} (prebuilt): ${pluginDir}`);
      continue;
    }
    try {
      await esbuildBuild({
        entryPoints: [entryFile.src],
        outfile: path.join(pluginDir, "index.mjs"),
        bundle: true,
        format: "esm",
        platform: "node",
        target: "node22",
        // openclaw runtime APIs come from the gateway, never bundle:
        external: [
          "openclaw/*",
          // node: built-ins (also auto-externalized by platform=node, but
          // listing explicitly is safer across esbuild versions):
          "node:*",
        ],
        // Source map is small + helps debug live errors:
        sourcemap: "inline",
        // Silence the dev-time warnings about node built-ins:
        logLevel: "warning",
      });
    } catch (err) {
      console.error(
        `install openclaw: esbuild failed for ${plugin.displayName}: ${(err as Error).message}`,
      );
      return 1;
    }

    // Minimal package.json — no deps (everything's bundled), but we still
    // emit `openclaw.extensions` so the gateway's discovery sees it as
    // an openclaw plugin under the new extensions schema.
    const pkgJson = {
      name: `${plugin.pluginDirname}-extension`,
      version: "0.0.0-local",
      private: true,
      type: "module",
      description: `Bundled install of ${plugin.pluginDirname} (esbuild-produced single-file plugin entry). Auto-generated by \`digital-me install --runtime openclaw\`.`,
      openclaw: { extensions: ["./index.mjs"] },
      // Enforced compatibility floor — openclaw refuses to load on an older
      // host. Source of truth: @digital-me/runtime-openclaw compat.ts.
      install: { minHostVersion: OPENCLAW_MIN_HOST_VERSION },
    };
    writeFileSync(
      path.join(pluginDir, OPENCLAW_EXTENSION_PACKAGE_JSON),
      JSON.stringify(pkgJson, null, 2) + "\n",
      "utf-8",
    );

    // No npm install needed — the bundle is self-contained.

    console.log(`[OK] installed ${plugin.displayName}: ${pluginDir}`);
  }

  // Ship the shared cli-exec worker so `cli_exec_aliases` (e.g. claude-code-cli)
  // actually resolve. The brain's alias resolver bakes a task command pointing
  // at `<extensionsDir>/scripts/cli-exec-worker.mjs` (one level up from each
  // plugin dir); without this file the worker fails ENOENT and every cli-exec
  // task dies. The worker is a plain node-builtins script — copy it verbatim.
  const cliExecScriptsDir = path.join(target, "scripts");
  mkdirSync(cliExecScriptsDir, { recursive: true });
  copyFileSync(
    OPENCLAW_CLI_EXEC_WORKER_SCRIPT,
    path.join(cliExecScriptsDir, "cli-exec-worker.mjs"),
  );
  console.log(
    `[OK] installed cli-exec worker: ${path.join(cliExecScriptsDir, "cli-exec-worker.mjs")}`,
  );

  return 0;
}
